all: django-mode.el revive.el revive.el windows.el winhist.el

#winring.el:
#	wget http://www.python.org/emacs/winring/winring.el

winhist.el:
	wget http://www.bookshelf.jp/elc/winhist.el

rst-mode.el:
	wget http://www.merten-home.de/FreeSoftware/rst-mode/rst-mode.el

rst.el:
	wget http://svn.berlios.de/viewcvs/*checkout*/docutils/tags/docutils-0.5/tools/editors/emacs/rst.el

django-mode.el:
	wget http://code.unicoders.org/export/117/hacks/trunk/django-mode.el

revive.el:
	wget http://www.gentei.org/~yuuji/software/revive.el

windows.el:
	wget http://www.gentei.org/~yuuji/software/windows.el

color-theme-6.6.0/: get-color-theme.sh
	sh get-color-theme.sh
