all: rst-mode.el django-mode.el revive.el revive.el windows.el

rst-mode.el:
	wget http://www.merten-home.de/FreeSoftware/rst-mode/rst-mode.el

django-mode.el:
	wget http://code.unicoders.org/export/117/hacks/trunk/django-mode.el

revive.el:
	wget http://www.gentei.org/~yuuji/software/revive.el

windows.el:
	wget http://www.gentei.org/~yuuji/software/windows.el

color-theme-6.6.0/: color-theme-6.6.0.tar.gz
	sh get-color-theme.sh
